import {A} from "../data/anatomy.js";import {skeleton} from "./skeleton.js";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const keys=Object.keys(A);let state={view:"front",sel:"skull",zoom:1,xp:+localStorage.getItem("axp")||0,seen:new Set(JSON.parse(localStorage.getItem("axseen")||"[]")),mission:+localStorage.getItem("axmission")||0,streak:+localStorage.getItem("axstreak")||0};
function save(){localStorage.setItem("axp",state.xp);localStorage.setItem("axseen",JSON.stringify([...state.seen]));localStorage.setItem("axmission",state.mission);localStorage.setItem("axstreak",state.streak)}
function render(){let v=$("#viewer");v.innerHTML=skeleton(state.view);v.querySelector("svg").style.transform=`scale(${state.zoom})`;v.querySelectorAll("[data-id]").forEach(e=>{e.classList.toggle("selected",e.dataset.id===state.sel);e.addEventListener("click",()=>select(e.dataset.id))});$("#viewTitle").textContent={front:"Anterior View",back:"Posterior View",left:"Left Lateral View",right:"Right Lateral View"}[state.view];stats()}
function select(id,award=true){if(!A[id])return;state.sel=id;state.seen.add(id);if(award){state.xp+=5;state.mission=Math.min(5,state.mission+1);state.streak++;save()}render();details();stats()}
function details(){let d=A[state.sel];$("#details").innerHTML=`<div class="eyebrow">${d.type} · ${d.region}</div><div class="name">${d.name}</div><div class="also">Also known as: ${d.alt.join(", ")}</div><div class="rule"></div><h3>⚡ Function</h3><p>${d.fn}</p><h3>🔗 Articulates / connects with</h3><div class="chips">${d.art.map(x=>`<span class="chip">${x}</span>`).join("")}</div><h3>📍 Important landmarks</h3><div class="chips">${d.land.map(x=>`<span class="chip">${x}</span>`).join("")}</div><div class="rule"></div><p style="color:var(--muted)">Study challenge: point to it on the model, say its name, then explain its function without looking.</p>`}
function stats(){let pct=Math.round(state.seen.size/keys.length*100);$("#xpTop").textContent=`${state.xp} XP`;$(`#streakTop`).textContent=`🔥 ${state.streak}`;$("#coverage").textContent=pct+"%";$("#missionCount").textContent=`${state.mission}/5`;$("#missionBar").style.width=(state.mission/5*100)+"%";$("#missionText").textContent=state.mission>=5?"Mission complete! 🎉":"Identify 5 structures correctly."}
$$(".view").forEach(b=>b.onclick=()=>{$$(".view").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.view=b.dataset.view;render()});
$("#zoomIn").onclick=()=>{state.zoom=Math.min(1.3,state.zoom+.1);render()};$("#zoomOut").onclick=()=>{state.zoom=Math.max(.75,state.zoom-.1);render()};$("#zoomReset").onclick=()=>{state.zoom=1;render()};
$("#themeBtn").onclick=()=>{document.body.classList.toggle("light");$("#themeBtn").textContent=document.body.classList.contains("light")?"☀":"☾"};
$("#search").oninput=e=>{let q=e.target.value.trim().toLowerCase(),box=$("#results");if(!q){box.classList.remove("open");box.innerHTML="";return}let hits=keys.filter(k=>{let d=A[k];return(d.name+" "+d.alt.join(" ")+" "+d.region+" "+d.type+" "+d.land.join(" ")).toLowerCase().includes(q)}).slice(0,9);box.innerHTML=hits.map(k=>`<button class="result" data-k="${k}"><b>${A[k].name}</b><br><small>${A[k].type} · ${A[k].region}</small></button>`).join("");box.classList.toggle("open",hits.length>0);box.querySelectorAll("[data-k]").forEach(b=>b.onclick=()=>{select(b.dataset.k,false);box.classList.remove("open");e.target.value=""})};
function modal(html){$("#modalContent").innerHTML=html;$("#modal").classList.remove("hidden")}$("#closeModal").onclick=()=>$("#modal").classList.add("hidden");$("#modal").onclick=e=>{if(e.target.id==="modal")$("#modal").classList.add("hidden")};
function quiz(){let score=0,total=0;function q(){let correct=keys[Math.floor(Math.random()*keys.length)],opts=[correct];while(opts.length<4){let x=keys[Math.floor(Math.random()*keys.length)];if(!opts.includes(x))opts.push(x)}opts.sort(()=>Math.random()-.5);modal(`<div class="eyebrow">⚡ RAPID FIRE</div><h2>Identify the structure</h2><div class="quiz-big">${A[correct].name}</div><p style="color:var(--muted)">Choose the matching structure.</p><div class="options">${opts.map(k=>`<button class="option" data-k="${k}">${A[k].name}</button>`).join("")}</div><p style="color:var(--muted">Score: ${score}/${total}</p>`);$("#modalContent").querySelectorAll(".option").forEach(b=>b.onclick=()=>{total++;if(b.dataset.k===correct){score++;b.classList.add("correct");state.xp+=25;state.mission=Math.min(5,state.mission+1);state.streak++;save()}else{b.classList.add("wrong");$("#modalContent").querySelector(`[data-k="${correct}"]`).classList.add("correct")}setTimeout(q,650)})}q()}
$("#quizBtn").onclick=quiz;
$$(".quick-grid button").forEach(b=>b.onclick=()=>{let m=b.dataset.tool;if(m==="random"){select(keys[Math.floor(Math.random()*keys.length)]);return}if(m==="flash"){let d=A[state.sel];modal(`<div class="eyebrow">🃏 FLASHCARD</div><h2>${d.name}</h2><p>Also known as: ${d.alt.join(", ")}</p><hr><p><b>Function:</b> ${d.fn}</p><p><b>Landmarks:</b> ${d.land.join(", ")}</p>`);return}if(m==="progress"){modal(`<div class="eyebrow">🏆 YOUR ATLAS</div><h2>Progress</h2><div class="stats"><div class="stat"><b>${state.xp}</b><small>XP</small></div><div class="stat"><b>${state.seen.size}</b><small>Structures seen</small></div><div class="stat"><b>${Math.round(state.seen.size/keys.length*100)}%</b><small>Atlas explored</small></div></div>`);return}modal(`<div class="eyebrow">🧭 ANATOMY MAP</div><h2>Study Regions</h2><div class="chips">${["Head","Spine","Thorax","Shoulder","Upper limb","Forearm","Hand","Pelvis","Lower limb","Knee","Foot"].map(r=>`<button class="chip" data-region="${r}">${r}</button>`).join("")}</div><p style="margin-top:18px;color:var(--muted)">Use Search to jump directly to structures in each region.</p>`)});
render();details();stats();
